services:
  ftse100-scraper:
    build: .
    container_name: ftse100-scraper
    environment:
      - CLICKHOUSE_HOST=10.10.1.30
      - CLICKHOUSE_PORT=8333
      - CLICKHOUSE_USER=johnp
      - CLICKHOUSE_PASSWORD=test123
      - CLICKHOUSE_DATABASE=garden
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M